name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gcc-version: 9
          - os: ubuntu-latest
            gcc-version: 11
          - os: macos-latest
            gcc-version: 14
          - os: macos-latest
            gcc-version: 15

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC ${{ matrix.gcc-version }}
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }}
        echo "CC=gcc-${{ matrix.gcc-version }}" >> $GITHUB_ENV
        echo "CXX=g++-${{ matrix.gcc-version }}" >> $GITHUB_ENV

    - name: Install GCC ${{ matrix.gcc-version }}
      if: matrix.os == 'macos-latest'
      run: |
        brew install gcc@${{ matrix.gcc-version }}
        echo "CC=gcc-${{ matrix.gcc-version }}" >> $GITHUB_ENV
        echo "CXX=g++-${{ matrix.gcc-version }}" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        make test
